import { createContext, useContext, useState, ReactNode } from "react";

type Language = "pt" | "en" | "fr" | "de" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Header
    "header.search": "Pesquisar por evento, local ou cidade",
    "header.login": "Entrar / Registar",
    "header.getApp": "OBTER A APP",
    "header.advertise": "Anunciar Evento",
    
    // Search Modal
    "search.title": "Pesquisar Eventos",
    "search.popular": "Eventos Mais Populares",
    
    // Hero
    "hero.title1": "DESCOBRE",
    "hero.title2": "OS MELHORES",
    "hero.title3": "EVENTOS AO VIVO",
    "hero.description": "Espetáculos incríveis ao vivo. Preços transparentes. Recomendações relevantes. Descarrega o Lyven e começa a descobrir eventos fantásticos perto de ti.",
    "hero.download": "DESCARREGAR LYVEN",
    "hero.browse": "Explorar Eventos",
    "hero.noFees": "Sem taxas ocultas",
    "hero.instant": "Bilhetes instantâneos",
    "hero.bestPrices": "Melhores preços",
    
    // Events
    "events.trending": "Em Destaque em",
    "events.city": "Lisboa",
    "events.description": "Descobre alguns dos eventos mais populares que vêm aí na tua cidade, desde noites de clube e concertos a showcases de artistas e performances intimistas.",
    "events.swipe": "Desliza para mais",
    "events.browseAll": "Explorar todos os eventos",
    "events.swipeMore": "Desliza para explorar mais",
    "events.getTickets": "Obter Bilhetes",
    
    // Footer
    "footer.description": "O futuro da descoberta de eventos. Descarrega o Lyven para encontrar espetáculos incríveis ao vivo com preços transparentes e recomendações relevantes.",
    "footer.download": "Descarregar",
    "footer.events": "Eventos",
    "footer.browseEvents": "Explorar eventos",
    "footer.venues": "Locais",
    "footer.artists": "Artistas",
    "footer.categories": "Categorias",
    "footer.support": "Suporte",
    "footer.help": "Obter ajuda",
    "footer.safety": "Segurança",
    "footer.terms": "Termos de serviço",
    "footer.privacy": "Política de privacidade",
    
    // Advertise Event Page
    "advertise.hero.title": "Onde os Organizadores de Eventos Crescem",
    "advertise.hero.subtitle": "A plataforma completa de bilheteira e descoberta, confiada por milhares de organizadores e participantes em Portugal",
    "advertise.cta.getStarted": "Comece Gratuitamente",
    "advertise.cta.contactSales": "Contactar Vendas",
    "advertise.intro": "Crie eventos facilmente numa plataforma que os participantes adoram e confiam",
    "advertise.features.ticketing.title": "Bilheteira de Eventos",
    "advertise.features.ticketing.desc": "Venda mais bilhetes com páginas de eventos personalizáveis e uma experiência de checkout perfeita numa plataforma confiável",
    "advertise.features.analytics.title": "Relatórios & Análises",
    "advertise.features.analytics.desc": "Saiba mais sobre os seus compradores e descubra de onde vêm as vendas com análises em tempo real",
    "advertise.features.app.title": "App do Organizador",
    "advertise.features.app.desc": "Faça check-in de convidados, venda bilhetes à porta e acompanhe dados com a nossa aplicação fácil de usar",
    "advertise.marketplace.title": "Cresça a sua comunidade num marketplace onde milhões de pessoas procuram coisas para fazer",
    "advertise.marketplace.discovery.title": "Descoberta de Participantes",
    "advertise.marketplace.discovery.desc": "Recomendações personalizadas adaptadas aos interesses e localização dos participantes",
    "advertise.marketplace.ads.title": "Publicidade Lyven",
    "advertise.marketplace.ads.desc": "Promova o seu evento na Lyven e obtenha 14x mais visibilidade na nossa homepage e resultados de pesquisa",
    "advertise.marketplace.marketing.title": "Ferramentas de Marketing",
    "advertise.marketplace.marketing.desc": "Envolva participantes e alcance novos com o nosso conjunto de ferramentas automatizadas de email e marketing social",
    "advertise.tools.title": "Todas as ferramentas que precisa para organizar um evento e crescer a sua comunidade",
    "advertise.tools.ticketing.title": "Bilheteira de Eventos",
    "advertise.tools.ticketing.desc": "Tudo o que precisa para vender bilhetes para eventos presenciais ou online",
    "advertise.tools.ads.title": "Publicidade Lyven",
    "advertise.tools.ads.desc": "Crie anúncios sem complicações que promovem o seu evento na Lyven",
    "advertise.tools.marketing.title": "Ferramentas de Marketing",
    "advertise.tools.marketing.desc": "Todas as ferramentas de marketing que precisa num só lugar",
    "advertise.tools.payments.title": "Pagamentos",
    "advertise.tools.payments.desc": "Recolha e simplifique facilmente os pagamentos de eventos",
    "advertise.pricing.title": "Faça o que adora e ganhe mais dinheiro com taxas baixas e pagamentos rápidos",
    "advertise.pricing.lowFees.title": "Taxas Baixas",
    "advertise.pricing.lowFees.desc": "Valor claro, taxas transparentes. Para que se possa focar no que é importante.",
    "advertise.pricing.processing.title": "Processamento de Pagamentos",
    "advertise.pricing.processing.desc": "Recolha e simplifique facilmente os pagamentos com processamento integrado",
    "advertise.pricing.payouts.title": "Pagamentos Agendados",
    "advertise.pricing.payouts.desc": "Receba antes do seu evento acontecer num cronograma personalizado à sua escolha",
    "advertise.pricingSection.title": "Preços simples, valor claro",
    "advertise.pricingSection.subtitle": "Sem taxas antecipadas",
    "advertise.pricingSection.description": "Crie o seu evento no maior marketplace de eventos sem custos para si. Temos tudo o que precisa para vender bilhetes, gerir eventos e aumentar o volume de negócios.",
    "advertise.pricingSection.features.0": "Tipos de bilhetes flexíveis para eventos presenciais ou online",
    "advertise.pricingSection.features.1": "Páginas do evento ilimitadas no nosso marketplace",
    "advertise.pricingSection.features.2": "Ferramentas de marketing integradas",
    "advertise.pricingSection.features.3": "Venda bilhetes no seu próprio site",
    "advertise.pricingSection.features.4": "Experiência perfeita de checkout",
    "advertise.pricingSection.features.5": "Pagamentos antes do evento acontecer",
    "advertise.pricingSection.features.6": "Análises e relatórios detalhados",
    "advertise.pricingSection.attendeeFees": "Taxas baixas para os seus participantes",
    "advertise.pricingSection.freeEvents": "Sem taxas para eventos gratuitos",
    "advertise.pricingSection.serviceFee": "Taxa de serviço competitiva por bilhete",
    "advertise.pricingSection.note": "As taxas são pagas pelos compradores de bilhetes, a menos que opte por suportá-las.",
    "advertise.form.title": "Comece a anunciar hoje",
    "advertise.form.subtitle": "Preencha o formulário e a nossa equipa entrará em contacto",
    "advertise.form.name": "Nome",
    "advertise.form.email": "Email",
    "advertise.form.phone": "Telemóvel",
    "advertise.form.website": "Website",
    "advertise.form.city": "Cidade",
    "advertise.form.currency": "Moeda e Preço Médio",
    "advertise.form.submit": "Enviar Pedido",
    "advertise.form.submitting": "A enviar...",
    "advertise.form.success": "Pedido enviado!",
    "advertise.form.successDesc": "Entraremos em contacto em breve",
    "advertise.form.error": "Erro ao enviar",
    "advertise.form.errorDesc": "Por favor, tente novamente",
    "advertise.form.terms": "Ao submeter, aceita os nossos termos e condições",
  },
  en: {
    // Header
    "header.search": "Search by event, venue or city",
    "header.login": "Log in / Sign up",
    "header.getApp": "GET THE APP",
    "header.advertise": "Advertise Event",
    
    // Search Modal
    "search.title": "Search Events",
    "search.popular": "Most Popular Events",
    
    // Hero
    "hero.title1": "DISCOVER",
    "hero.title2": "THE BEST",
    "hero.title3": "LIVE EVENTS",
    "hero.description": "Incredible live shows. Upfront pricing. Relevant recommendations. Download Lyven and start discovering amazing events near you.",
    "hero.download": "DOWNLOAD LYVEN",
    "hero.browse": "Browse Events",
    "hero.noFees": "No hidden fees",
    "hero.instant": "Instant tickets",
    "hero.bestPrices": "Best prices",
    
    // Events
    "events.trending": "Trending in",
    "events.city": "New York",
    "events.description": "Check out some of the most popular events coming up in your city, from club nights and gigs to artist showcases and intimate performances.",
    "events.swipe": "Swipe left for more",
    "events.browseAll": "Browse all events",
    "events.swipeMore": "Swipe to explore more",
    "events.getTickets": "Get Tickets",
    
    // Footer
    "footer.description": "The future of event discovery. Download Lyven to find incredible live shows with upfront pricing and relevant recommendations.",
    "footer.download": "Download",
    "footer.events": "Events",
    "footer.browseEvents": "Browse events",
    "footer.venues": "Venues",
    "footer.artists": "Artists",
    "footer.categories": "Categories",
    "footer.support": "Support",
    "footer.help": "Get help",
    "footer.safety": "Safety",
    "footer.terms": "Terms of service",
    "footer.privacy": "Privacy policy",
    
    // Advertise Event Page
    "advertise.hero.title": "Where Event Organizers Grow",
    "advertise.hero.subtitle": "The all-in-one ticketing and discovery platform trusted by thousands of organizers and attendees in Portugal",
    "advertise.cta.getStarted": "Get Started for Free",
    "advertise.cta.contactSales": "Contact Sales",
    "advertise.intro": "Easily create events on a platform that attendees love and trust",
    "advertise.features.ticketing.title": "Event Ticketing",
    "advertise.features.ticketing.desc": "Sell more tickets with customizable event pages and a seamless checkout experience on a trusted platform",
    "advertise.features.analytics.title": "Reporting & Analytics",
    "advertise.features.analytics.desc": "Learn more about your buyers and discover where sales are coming from with real-time analytics",
    "advertise.features.app.title": "Organizer App",
    "advertise.features.app.desc": "Check guests in, sell tickets at the door, and track data with our easy-to-use app",
    "advertise.marketplace.title": "Grow your community on a marketplace where millions of people look for things to do",
    "advertise.marketplace.discovery.title": "Attendee Discovery",
    "advertise.marketplace.discovery.desc": "Personalized recommendations tailored to attendees' interests and location",
    "advertise.marketplace.ads.title": "Lyven Ads",
    "advertise.marketplace.ads.desc": "Promote your event across Lyven and get 14x more visibility on our homepage and search results",
    "advertise.marketplace.marketing.title": "Marketing Tools",
    "advertise.marketplace.marketing.desc": "Engage attendees and reach new ones with our suite of automated email and social marketing tools",
    "advertise.tools.title": "All the tools you need to host an event & grow your community",
    "advertise.tools.ticketing.title": "Event Ticketing",
    "advertise.tools.ticketing.desc": "Everything you need to sell tickets for in-person or online events",
    "advertise.tools.ads.title": "Lyven Ads",
    "advertise.tools.ads.desc": "Create no-hassle ads that promote your event on Lyven",
    "advertise.tools.marketing.title": "Marketing Tools",
    "advertise.tools.marketing.desc": "All the event marketing tools you need in one place",
    "advertise.tools.payments.title": "Payments",
    "advertise.tools.payments.desc": "Easily collect and simplify event payments",
    "advertise.pricing.title": "Do what you love and earn more money with low-cost fees and quicker payouts",
    "advertise.pricing.lowFees.title": "Low-cost fees",
    "advertise.pricing.lowFees.desc": "Clear value, transparent fees. So you can focus on the important things.",
    "advertise.pricing.processing.title": "Payment Processing",
    "advertise.pricing.processing.desc": "Easily collect and simplify event payments with built-in payment processing",
    "advertise.pricing.payouts.title": "Scheduled Payouts",
    "advertise.pricing.payouts.desc": "Get paid before your event takes place on a customized schedule of your choice",
    "advertise.pricingSection.title": "Simple pricing, clear value",
    "advertise.pricingSection.subtitle": "No upfront fees",
    "advertise.pricingSection.description": "Create your event on the largest event marketplace at no cost to you. We have everything you need to sell tickets, manage events and grow your business.",
    "advertise.pricingSection.features.0": "Flexible ticket types for in-person or online events",
    "advertise.pricingSection.features.1": "Unlimited event pages on our marketplace",
    "advertise.pricingSection.features.2": "Built-in marketing tools",
    "advertise.pricingSection.features.3": "Sell tickets on your own website",
    "advertise.pricingSection.features.4": "Seamless checkout experience",
    "advertise.pricingSection.features.5": "Get paid before your event",
    "advertise.pricingSection.features.6": "Detailed analytics and reports",
    "advertise.pricingSection.attendeeFees": "Low fees for your attendees",
    "advertise.pricingSection.freeEvents": "No fees for free events",
    "advertise.pricingSection.serviceFee": "Competitive service fee per ticket",
    "advertise.pricingSection.note": "Fees are paid by ticket buyers, unless you choose to cover them.",
    "advertise.form.title": "Start advertising today",
    "advertise.form.subtitle": "Fill out the form and our team will contact you",
    "advertise.form.name": "Name",
    "advertise.form.email": "Email",
    "advertise.form.phone": "Phone",
    "advertise.form.website": "Website",
    "advertise.form.city": "City",
    "advertise.form.currency": "Currency and Average Price",
    "advertise.form.submit": "Submit Request",
    "advertise.form.submitting": "Submitting...",
    "advertise.form.success": "Request sent!",
    "advertise.form.successDesc": "We will contact you soon",
    "advertise.form.error": "Error sending",
    "advertise.form.errorDesc": "Please try again",
    "advertise.form.terms": "By submitting, you accept our terms and conditions",
  },
  fr: {
    // Header
    "header.search": "Rechercher par événement, lieu ou ville",
    "header.login": "Connexion / Inscription",
    "header.getApp": "OBTENIR L'APP",
    "header.advertise": "Annoncer un Événement",
    
    // Search Modal
    "search.title": "Rechercher des Événements",
    "search.popular": "Événements les Plus Populaires",
    
    // Hero
    "hero.title1": "DÉCOUVREZ",
    "hero.title2": "LES MEILLEURS",
    "hero.title3": "ÉVÉNEMENTS EN DIRECT",
    "hero.description": "Des spectacles incroyables en direct. Tarifs transparents. Recommandations pertinentes. Téléchargez Lyven et commencez à découvrir des événements extraordinaires près de chez vous.",
    "hero.download": "TÉLÉCHARGER LYVEN",
    "hero.browse": "Parcourir les Événements",
    "hero.noFees": "Pas de frais cachés",
    "hero.instant": "Billets instantanés",
    "hero.bestPrices": "Meilleurs prix",
    
    // Events
    "events.trending": "Tendances à",
    "events.city": "Paris",
    "events.description": "Découvrez certains des événements les plus populaires à venir dans votre ville, des soirées en club aux concerts en passant par les showcases d'artistes et les performances intimistes.",
    "events.swipe": "Glissez pour plus",
    "events.browseAll": "Parcourir tous les événements",
    "events.swipeMore": "Glissez pour explorer plus",
    "events.getTickets": "Obtenir des Billets",
    
    // Footer
    "footer.description": "L'avenir de la découverte d'événements. Téléchargez Lyven pour trouver des spectacles incroyables en direct avec des tarifs transparents et des recommandations pertinentes.",
    "footer.download": "Télécharger",
    "footer.events": "Événements",
    "footer.browseEvents": "Parcourir les événements",
    "footer.venues": "Lieux",
    "footer.artists": "Artistes",
    "footer.categories": "Catégories",
    "footer.support": "Support",
    "footer.help": "Obtenir de l'aide",
    "footer.safety": "Sécurité",
    "footer.terms": "Conditions d'utilisation",
    "footer.privacy": "Politique de confidentialité",
    
    // Advertise Event Page
    "advertise.hero.title": "Où les Organisateurs d'Événements Grandissent",
    "advertise.hero.subtitle": "La plateforme complète de billetterie et découverte, approuvée par des milliers d'organisateurs au Portugal",
    "advertise.cta.getStarted": "Commencer Gratuitement",
    "advertise.cta.contactSales": "Contacter les Ventes",
    "advertise.intro": "Créez facilement des événements sur une plateforme que les participants adorent",
    "advertise.features.ticketing.title": "Billetterie d'Événements",
    "advertise.features.ticketing.desc": "Vendez plus de billets avec des pages personnalisables et une expérience de paiement fluide",
    "advertise.features.analytics.title": "Rapports & Analyses",
    "advertise.features.analytics.desc": "Découvrez vos acheteurs avec des analyses en temps réel",
    "advertise.features.app.title": "App Organisateur",
    "advertise.features.app.desc": "Enregistrez les invités et vendez des billets facilement",
    "advertise.marketplace.title": "Développez votre communauté sur un marketplace où des millions cherchent des événements",
    "advertise.marketplace.discovery.title": "Découverte de Participants",
    "advertise.marketplace.discovery.desc": "Recommandations personnalisées adaptées aux intérêts des participants",
    "advertise.marketplace.ads.title": "Publicité Lyven",
    "advertise.marketplace.ads.desc": "Promouvez votre événement et obtenez 14x plus de visibilité",
    "advertise.marketplace.marketing.title": "Outils Marketing",
    "advertise.marketplace.marketing.desc": "Engagez les participants avec nos outils automatisés",
    "advertise.tools.title": "Tous les outils dont vous avez besoin",
    "advertise.tools.ticketing.title": "Billetterie",
    "advertise.tools.ticketing.desc": "Tout pour vendre des billets",
    "advertise.tools.ads.title": "Publicité",
    "advertise.tools.ads.desc": "Créez des annonces facilement",
    "advertise.tools.marketing.title": "Marketing",
    "advertise.tools.marketing.desc": "Tous les outils marketing en un lieu",
    "advertise.tools.payments.title": "Paiements",
    "advertise.tools.payments.desc": "Collectez les paiements facilement",
    "advertise.pricing.title": "Faites ce que vous aimez avec des frais bas",
    "advertise.pricing.lowFees.title": "Frais Bas",
    "advertise.pricing.lowFees.desc": "Valeur claire, frais transparents",
    "advertise.pricing.processing.title": "Traitement des Paiements",
    "advertise.pricing.processing.desc": "Collectez les paiements facilement",
    "advertise.pricing.payouts.title": "Paiements Programmés",
    "advertise.pricing.payouts.desc": "Soyez payé avant votre événement",
    "advertise.pricingSection.title": "Prix simples, valeur claire",
    "advertise.pricingSection.subtitle": "Sans frais initiaux",
    "advertise.pricingSection.description": "Créez votre événement sans frais pour vous",
    "advertise.pricingSection.features.0": "Types de billets flexibles",
    "advertise.pricingSection.features.1": "Pages d'événements illimitées",
    "advertise.pricingSection.features.2": "Outils marketing intégrés",
    "advertise.pricingSection.features.3": "Vendez sur votre site",
    "advertise.pricingSection.features.4": "Expérience de paiement fluide",
    "advertise.pricingSection.features.5": "Paiements avant l'événement",
    "advertise.pricingSection.features.6": "Analyses détaillées",
    "advertise.pricingSection.attendeeFees": "Frais bas pour vos participants",
    "advertise.pricingSection.freeEvents": "Sans frais pour événements gratuits",
    "advertise.pricingSection.serviceFee": "Frais de service compétitifs",
    "advertise.pricingSection.note": "Les frais sont payés par les acheteurs",
    "advertise.form.title": "Commencez aujourd'hui",
    "advertise.form.subtitle": "Remplissez le formulaire",
    "advertise.form.name": "Nom",
    "advertise.form.email": "Email",
    "advertise.form.phone": "Téléphone",
    "advertise.form.website": "Site web",
    "advertise.form.city": "Ville",
    "advertise.form.currency": "Devise et Prix Moyen",
    "advertise.form.submit": "Envoyer",
    "advertise.form.submitting": "Envoi...",
    "advertise.form.success": "Demande envoyée!",
    "advertise.form.successDesc": "Nous vous contacterons bientôt",
    "advertise.form.error": "Erreur",
    "advertise.form.errorDesc": "Veuillez réessayer",
    "advertise.form.terms": "En soumettant, vous acceptez nos conditions",
  },
  de: {
    // Header
    "header.search": "Nach Event, Veranstaltungsort oder Stadt suchen",
    "header.login": "Anmelden / Registrieren",
    "header.getApp": "APP HERUNTERLADEN",
    "header.advertise": "Event Bewerben",
    
    // Search Modal
    "search.title": "Events Suchen",
    "search.popular": "Beliebteste Events",
    
    // Hero
    "hero.title1": "ENTDECKE",
    "hero.title2": "DIE BESTEN",
    "hero.title3": "LIVE EVENTS",
    "hero.description": "Unglaubliche Live-Shows. Transparente Preise. Relevante Empfehlungen. Laden Sie Lyven herunter und beginnen Sie, fantastische Events in Ihrer Nähe zu entdecken.",
    "hero.download": "LYVEN HERUNTERLADEN",
    "hero.browse": "Events Durchsuchen",
    "hero.noFees": "Keine versteckten Gebühren",
    "hero.instant": "Sofortige Tickets",
    "hero.bestPrices": "Beste Preise",
    
    // Events
    "events.trending": "Trending in",
    "events.city": "Berlin",
    "events.description": "Schauen Sie sich einige der beliebtesten kommenden Events in Ihrer Stadt an, von Clubnächten und Konzerten bis hin zu Künstler-Showcases und intimen Aufführungen.",
    "events.swipe": "Wischen Sie für mehr",
    "events.browseAll": "Alle Events durchsuchen",
    "events.swipeMore": "Wischen Sie, um mehr zu erkunden",
    "events.getTickets": "Tickets Kaufen",
    
    // Footer
    "footer.description": "Die Zukunft der Event-Entdeckung. Laden Sie Lyven herunter, um unglaubliche Live-Shows mit transparenten Preisen und relevanten Empfehlungen zu finden.",
    "footer.download": "Herunterladen",
    "footer.events": "Events",
    "footer.browseEvents": "Events durchsuchen",
    "footer.venues": "Veranstaltungsorte",
    "footer.artists": "Künstler",
    "footer.categories": "Kategorien",
    "footer.support": "Support",
    "footer.help": "Hilfe erhalten",
    "footer.safety": "Sicherheit",
    "footer.terms": "Nutzungsbedingungen",
    "footer.privacy": "Datenschutzrichtlinie",
    
    // Advertise Event Page
    "advertise.hero.title": "Stärken Sie Event-Ersteller, Promoter und Veranstaltungsorte durch Daten und Technologie",
    "advertise.hero.subtitle": "Entfalten Sie das volle Potenzial Ihres Events mit Lyven",
    "advertise.benefit1.title": "Erweitern Sie Ihr Publikum",
    "advertise.benefit1.desc": "Erreichen Sie Millionen an Events interessierter Nutzer",
    "advertise.benefit2.title": "Maximieren Sie Verkäufe und Umsatz",
    "advertise.benefit2.desc": "Intelligente Tools zur Optimierung Ihrer Verkäufe",
    "advertise.benefit3.title": "Vereinfachte Ticketverwaltung",
    "advertise.benefit3.desc": "Vollständiges und einfach zu verwaltendes System",
    "advertise.benefit4.title": "Steigern Sie die Kundenzufriedenheit",
    "advertise.benefit4.desc": "Perfektes Erlebnis von Anfang bis Ende",
    "advertise.stats.users": "Millionen",
    "advertise.stats.usersDesc": "Nutzer vertrauen unserer Plattform",
    "advertise.stats.events": "150K+",
    "advertise.stats.eventsDesc": "Events warten darauf, erlebt zu werden",
    "advertise.stats.cities": "200+",
    "advertise.stats.citiesDesc": "Städte in über 30 Ländern",
    "advertise.stats.rating": "4.8/5",
    "advertise.stats.ratingDesc": "Kundenbewertung",
    "advertise.form.title": "Starten Sie Heute",
    "advertise.form.subtitle": "Füllen Sie das Formular aus und wir werden uns mit Ihnen in Verbindung setzen, um Ihre Registrierung zu genehmigen",
    "advertise.form.name": "Vollständiger Name",
    "advertise.form.email": "Email",
    "advertise.form.phone": "Telefon",
    "advertise.form.website": "Webseite",
    "advertise.form.city": "Stadt",
    "advertise.form.currency": "Währung und durchschnittlicher Ticketpreis",
    "advertise.form.submit": "Anfrage Senden",
    "advertise.form.submitting": "Wird gesendet...",
    "advertise.form.terms": "Mit dem Absenden stimmen Sie unseren Allgemeinen Geschäftsbedingungen zu. Wir werden Sie in Kürze kontaktieren, um Ihre Registrierung zu genehmigen.",
    "advertise.form.success": "Anfrage erfolgreich gesendet!",
    "advertise.form.successDesc": "Wir werden Sie in Kürze kontaktieren, um Ihre Registrierung zu genehmigen.",
    "advertise.form.error": "Fehler beim Senden",
    "advertise.form.errorDesc": "Bitte versuchen Sie es erneut oder kontaktieren Sie uns direkt unter info@lyven.pt",
  },
  es: {
    // Header
    "header.search": "Buscar por evento, lugar o ciudad",
    "header.login": "Iniciar sesión / Registrarse",
    "header.getApp": "OBTENER LA APP",
    "header.advertise": "Anunciar Evento",
    
    // Search Modal
    "search.title": "Buscar Eventos",
    "search.popular": "Eventos Más Populares",
    
    // Hero
    "hero.title1": "DESCUBRE",
    "hero.title2": "LOS MEJORES",
    "hero.title3": "EVENTOS EN VIVO",
    "hero.description": "Increíbles espectáculos en vivo. Precios transparentes. Recomendaciones relevantes. Descarga Lyven y comienza a descubrir eventos increíbles cerca de ti.",
    "hero.download": "DESCARGAR LYVEN",
    "hero.browse": "Explorar Eventos",
    "hero.noFees": "Sin tarifas ocultas",
    "hero.instant": "Entradas instantáneas",
    "hero.bestPrices": "Mejores precios",
    
    // Events
    "events.trending": "Tendencias en",
    "events.city": "Madrid",
    "events.description": "Descubre algunos de los eventos más populares que se avecinan en tu ciudad, desde noches de club y conciertos hasta showcases de artistas y actuaciones íntimas.",
    "events.swipe": "Desliza para más",
    "events.browseAll": "Explorar todos los eventos",
    "events.swipeMore": "Desliza para explorar más",
    "events.getTickets": "Obtener Entradas",
    
    // Footer
    "footer.description": "El futuro del descubrimiento de eventos. Descarga Lyven para encontrar increíbles espectáculos en vivo con precios transparentes y recomendaciones relevantes.",
    "footer.download": "Descargar",
    "footer.events": "Eventos",
    "footer.browseEvents": "Explorar eventos",
    "footer.venues": "Lugares",
    "footer.artists": "Artistas",
    "footer.categories": "Categorías",
    "footer.support": "Soporte",
    "footer.help": "Obtener ayuda",
    "footer.safety": "Seguridad",
    "footer.terms": "Términos de servicio",
    "footer.privacy": "Política de privacidad",
    
    // Advertise Event Page
    "advertise.hero.title": "Potencie a creadores de eventos, promotores y venues a través de datos y tecnología",
    "advertise.hero.subtitle": "Desbloquea todo el potencial de tu evento con Lyven",
    "advertise.benefit1.title": "Amplía tu audiencia",
    "advertise.benefit1.desc": "Alcanza millones de usuarios interesados en eventos",
    "advertise.benefit2.title": "Maximiza ventas e ingresos",
    "advertise.benefit2.desc": "Herramientas inteligentes para optimizar tus ventas",
    "advertise.benefit3.title": "Gestión de entradas simplificada",
    "advertise.benefit3.desc": "Sistema completo y fácil de gestionar",
    "advertise.benefit4.title": "Aumenta la satisfacción del cliente",
    "advertise.benefit4.desc": "Experiencia perfecta de principio a fin",
    "advertise.stats.users": "Millones",
    "advertise.stats.usersDesc": "de usuarios confían en nuestra plataforma",
    "advertise.stats.events": "150K+",
    "advertise.stats.eventsDesc": "eventos esperando ser vividos",
    "advertise.stats.cities": "200+",
    "advertise.stats.citiesDesc": "ciudades en más de 30 países",
    "advertise.stats.rating": "4.8/5",
    "advertise.stats.ratingDesc": "calificación de clientes",
    "advertise.form.title": "Comienza Hoy",
    "advertise.form.subtitle": "Completa el formulario y nos pondremos en contacto para aprobar tu registro",
    "advertise.form.name": "Nombre completo",
    "advertise.form.email": "Email",
    "advertise.form.phone": "Teléfono",
    "advertise.form.website": "Sitio web",
    "advertise.form.city": "Ciudad",
    "advertise.form.currency": "Moneda y precio promedio de entrada",
    "advertise.form.submit": "Enviar Solicitud",
    "advertise.form.submitting": "Enviando...",
    "advertise.form.terms": "Al enviar, aceptas nuestros términos y condiciones. Nos pondremos en contacto pronto para aprobar tu registro.",
    "advertise.form.success": "¡Solicitud enviada con éxito!",
    "advertise.form.successDesc": "Nos pondremos en contacto pronto para aprobar tu registro.",
    "advertise.form.error": "Error al enviar",
    "advertise.form.errorDesc": "Por favor, inténtalo de nuevo o contáctanos directamente en info@lyven.pt",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("pt");

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
